### ISSUE TITLE
Add Twitter Card

### ISSUE THREAD

**Issue by jamespure** [jamespure/react_portfolio#1]

**Comment by C-Y-P-H-E-R** [comment]
Hey James!
I ran your portfolio. I had a doubt regarding the issue you created.
where do you want to insert the twitter card - in the contact us section below your github and linkedin ?

**Comment by jamespure** [comment]
> Hey James! I ran your portfolio. I had a doubt regarding the issue you created. where do you want to insert the twitter card - in the contact us section below your github and LinkedIn ?

Hey kushagra, thank you for the offer to help. However, this wasn't meant to be open source.
If you do would like to help. The Twitter card is a metadata that shows on Twitter when posting link

**Comment by C-Y-P-H-E-R** [comment]
alright, would still like to contribute since i'm looking forward to create something similar myself.
although there are multiple ways we can render twitter cards, which way do you want them ?

1. Summary Card:  Title, description, and thumbnail.
2. Summary Card with Large Image: Similar to the Summary Card, but with a prominently-featured image.
3. App Card: A Card with a direct download to a mobile app.
4. Player Card: A Card that can display video/audio/media.

![image](https://user-images.githubusercontent.com/69472040/175784177-7a059d89-c8de-4d7a-bf18-b7b9b145fc7b.png)

PS: above image is a simple summary card (number 1 in the list).

**Comment by jamespure** [comment]
Awesome! By all means, go ahead. I was thinking Summary Card with Large Image: Similar to the Summary Card, but with a prominently featured image.

**Comment by C-Y-P-H-E-R** [comment]
Great!
and what about the card's placement ?
should we build another section for it or adjust it in an existing section (eg. about me)

**Comment by jamespure** [comment]
Yes, I was thinking to adjust it about me or the hero/banner.

**Comment by C-Y-P-H-E-R** [comment]
Hey James!
I think i have completed the twitter card task.
Actually the purpose of twitter cards is entirely different. i learnt it from this blog, please feel free to skim through it.
and now it works as described in this blog.
i'll be creating a branch named "twitter-cards" and push it.
Please let me know your thoughts too.

here is the link to the blog:
https://coderrocketfuel.com/article/add-twitter-card-data-to-a-next-js-and-react-website

**Comment by jamespure** [comment]
Hey, kushagra!

Please create a pull request.

**Comment by C-Y-P-H-E-R** [comment]
I have created the pull request.
There are no merge conflicts in the code.
